package no.sintef.fiskinfo.model.sprice

data class ReportViewModel (
    var observasjonstid: String = "",
    var status: String = "",
    var ww: String = "",
    var VV: String = "",
    var h: String = "",
    var N: String = "",
    var Nh: String = "",
    var Cl: String = "",
    var Cm: String = "",
    var Ch: String = "",
    var W1: String = "",
    var W2: String = "",
    var HW: String = "",
    var PW: String = "",
    var DW1: String = "",
    var PW1: String = "",
    var HW1: String = "",
    var DW2: String = "",
    var PW2: String = "",
    var HW2: String = "",
    var ff: String = "",
    var ci: String = "",
    var Si: String = "",
    var bi: String = "",
    var Di: String = "",
    var zi: String = "",
    var Is: String = "",
    var EsEs: String = "",
    var Rs: String = "",
    var LaLa: String = "",
    var LoLo: String = "",
    var TT: String = "",
    var PP: String = "",
    var ppp: String = "",
    var ppp_a: String = "",
    var Ds: String = "",
    var Vs: String = "",
)